# Importer
FROM rust:latest as builder

COPY . /project
WORKDIR /project
RUN cargo build --release

# ---
FROM ubuntu:latest

## Install PostgreSQL lib
RUN apt update \
    && apt install -y libpq-dev \
    && apt clean cache

## Copy import binary
COPY --from=builder /project/target/release/import /import

## Copy blog posts
COPY --from=builder /project/posts /posts

## Execute importer
ENV POSTS_PATH /posts 
ENV DATABASE_URL postgres://postgres:postgres@website_db:5432/postgres
CMD ["/import"]
